# Generated by Django 4.2.11 on 2024-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
