# Generated by Django 4.2.11 on 2024-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_data_api', '0002_product_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
